package lilliput

// #include "avcodec.hpp"
// #include "opencv.hpp"
import "C"

import (
	"encoding/json"
	"fmt"
	"image"
	"strings"
	"time"
)

const (
	// SpriteSheetGridColumns is the default number of columns in a sprite sheet grid.
	SpriteSheetGridColumns = 5

	// SpriteSheetTileMaxDim is the default maximum dimension (width or height) of each tile in pixels.
	SpriteSheetTileMaxDim = 160

	// SpriteSheetAbsoluteMaxTiles is the absolute upper limit on generated tiles,
	// preventing memory exhaustion from maliciously crafted rules or extremely long videos.
	SpriteSheetAbsoluteMaxTiles = 1000
)

// SpriteSheetIntervalRule defines how many tiles to generate for videos up to a certain duration.
type SpriteSheetIntervalRule struct {
	// MaxDuration is the maximum video duration this rule applies to.
	// Rules are evaluated in order; the first rule where video duration <= MaxDuration is selected.
	// A MaxDuration of 0 matches any duration (useful for the final fallback rule).
	MaxDuration time.Duration `json:"max_duration"`

	// Interval specifies the time between each captured tile.
	// If Interval is > 0, the number of tiles is calculated as Duration / Interval.
	// If Interval is 0, the number of tiles defaults to MaxTiles.
	Interval time.Duration `json:"interval"`

	// MaxTiles limits the maximum number of tiles that can be generated by this rule.
	// If the video length divided by Interval produces more than MaxTiles, it is capped at MaxTiles.
	// If Interval is 0, exactly MaxTiles are generated.
	MaxTiles int `json:"max_tiles"`
}

// DefaultSpriteSheetRules implements standard thresholds for tile generation.
// - ≤50s: 1 tile per second (up to 50)
// - ≤15min: exactly 50 evenly spaced tiles
// - >15min: exactly 100 evenly spaced tiles
var DefaultSpriteSheetRules = []SpriteSheetIntervalRule{
	{MaxDuration: 50 * time.Second, Interval: time.Second, MaxTiles: 50},
	{MaxDuration: 15 * time.Minute, Interval: 0, MaxTiles: 50},
	{MaxDuration: 0, Interval: 0, MaxTiles: 100},
}

// SpriteSheetOptions controls how a sprite sheet is generated.
type SpriteSheetOptions struct {
	// FileType controls the output format of the sprite sheet image.
	// Supported values: ".jpeg", ".webp", ".png"
	// Defaults to ".jpeg" if empty.
	FileType string

	// EncodeOptions controls encode quality, e.g. map[int]int{lilliput.JpegQuality: 80}
	EncodeOptions map[int]int

	// GridColumns overrides the default number of grid columns (default: 5).
	// Clamped to [1, 100] for safety.
	GridColumns int

	// TileMaxDim overrides the maximum tile dimension in pixels (default: 160).
	// Clamped to [1, 4096] for safety.
	TileMaxDim int

	// Rules defines the configuration for frame interval thresholds based on duration.
	// Rules are evaluated in order. If empty, DefaultSpriteSheetRules is used.
	Rules []SpriteSheetIntervalRule

	// AbsoluteMaxTiles is an upper safety limit on the total number of tiles that can be generated,
	// overriding any rule-based calculations to prevent memory exhaustion.
	// Default is 1000.
	AbsoluteMaxTiles int
}

// SpriteSheetTile describes the position of one tile within the sprite sheet.
type SpriteSheetTile struct {
	// TimestampSec is the video timestamp this tile was captured at, in seconds.
	TimestampSec float64 `json:"timestamp_sec"`
	// X is the tile's left edge in the sprite sheet image, in pixels.
	X int `json:"x"`
	// Y is the tile's top edge in the sprite sheet image, in pixels.
	Y int `json:"y"`
	// Width is the tile width in pixels.
	Width int `json:"width"`
	// Height is the tile height in pixels.
	Height int `json:"height"`
}

// SpriteSheetManifest describes a generated sprite sheet: its dimensions and tile map.
type SpriteSheetManifest struct {
	// SheetWidth is the total width of the sprite sheet image in pixels.
	SheetWidth int `json:"sheet_width"`
	// SheetHeight is the total height of the sprite sheet image in pixels.
	SheetHeight int `json:"sheet_height"`
	// TileWidth is the width of each tile (constant across all tiles).
	TileWidth int `json:"tile_width"`
	// TileHeight is the height of each tile (constant across all tiles).
	TileHeight int `json:"tile_height"`
	// GridColumns is the number of columns in the grid.
	GridColumns int `json:"grid_columns"`
	// Tiles contains one entry per tile, in row-major order.
	Tiles []SpriteSheetTile `json:"tiles"`
}

// MarshalJSON serializes the manifest to JSON.
func (m *SpriteSheetManifest) MarshalJSON() ([]byte, error) {
	type Alias SpriteSheetManifest
	return json.Marshal((*Alias)(m))
}

// WebVTT generates a WebVTT thumbnail track string from the manifest.
// urlTemplate should be the URL of the sprite sheet image (e.g. "https://cdn.example.com/sheet.jpg").
// It uses the JW Player #xywh= convention.
func (m *SpriteSheetManifest) WebVTT(urlTemplate string) string {
	var sb strings.Builder
	sb.WriteString("WEBVTT\n\n")
	for i, tile := range m.Tiles {
		var endSec float64
		if i+1 < len(m.Tiles) {
			endSec = m.Tiles[i+1].TimestampSec
		} else {
			endSec = tile.TimestampSec + 1
		}
		sb.WriteString(fmt.Sprintf("%s --> %s\n", formatVTTTime(tile.TimestampSec), formatVTTTime(endSec)))
		sb.WriteString(fmt.Sprintf("%s#xywh=%d,%d,%d,%d\n\n",
			urlTemplate, tile.X, tile.Y, tile.Width, tile.Height))
	}
	return sb.String()
}

// formatVTTTime formats a float64 seconds value as HH:MM:SS.mmm.
func formatVTTTime(sec float64) string {
	d := time.Duration(sec * float64(time.Second))
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	s := int(d.Seconds()) % 60
	ms := int(d.Milliseconds()) % 1000
	return fmt.Sprintf("%02d:%02d:%02d.%03d", h, m, s, ms)
}

// selectTimestamps returns the set of timestamps (in seconds) at which to extract tiles,
// given the video duration, configuration rules, and absolute bounds.
func selectTimestamps(duration time.Duration, rules []SpriteSheetIntervalRule, absMaxTiles int) []float64 {
	if duration <= 0 {
		return nil
	}
	if len(rules) == 0 {
		rules = DefaultSpriteSheetRules
	}
	if absMaxTiles <= 0 {
		absMaxTiles = SpriteSheetAbsoluteMaxTiles
	}

	var match SpriteSheetIntervalRule
	for _, rule := range rules {
		if rule.MaxDuration == 0 || duration <= rule.MaxDuration {
			match = rule
			break
		}
	}
	// Fallback to the last rule if none matched and no catch-all was present
	if match.MaxTiles == 0 && match.Interval == 0 && len(rules) > 0 {
		match = rules[len(rules)-1]
	}

	var count int
	if match.Interval > 0 {
		count = int(duration.Seconds() / match.Interval.Seconds())
	} else {
		count = match.MaxTiles
	}

	// Cap at the rule's specific limit
	if match.MaxTiles > 0 && count > match.MaxTiles {
		count = match.MaxTiles
	}
	// Cap at the absolute safety limit
	if count > absMaxTiles {
		count = absMaxTiles
	}
	if count <= 0 {
		count = 1
	}

	timestamps := make([]float64, count)
	if count == 1 {
		timestamps[0] = 0
		return timestamps
	}
	// Evenly distribute across [0, duration). Start slightly into the video
	// to avoid black first frames.
	step := duration.Seconds() / float64(count)
	for i := 0; i < count; i++ {
		timestamps[i] = step * float64(i)
	}
	return timestamps
}

// tileDimensions calculates the tile width/height given the video's source dimensions
// and the max tile dimension constraint.
func tileDimensions(srcWidth, srcHeight, maxDim int) (tileW, tileH int) {
	if srcWidth <= 0 || srcHeight <= 0 || maxDim <= 0 {
		return maxDim, maxDim
	}
	if srcWidth >= srcHeight {
		// landscape or square
		tileW = maxDim
		tileH = int(float64(maxDim) * float64(srcHeight) / float64(srcWidth))
	} else {
		// portrait
		tileH = maxDim
		tileW = int(float64(maxDim) * float64(srcWidth) / float64(srcHeight))
	}
	if tileW < 1 {
		tileW = 1
	}
	if tileH < 1 {
		tileH = 1
	}
	return tileW, tileH
}

// GenerateSpriteSheet extracts frames from the video Decoder d and assembles them
// into a sprite sheet image encoded into dst. It returns the encoded sprite sheet bytes,
// the manifest describing tile positions, and any error.
//
// d must be an avCodecDecoder (i.e. a video source). The caller is responsible for
// closing d after this call.
//
// dst should be a pre-allocated byte slice large enough for the output image. A
// typical allocation is 8MB for JPEG output.
func GenerateSpriteSheet(d Decoder, opt *SpriteSheetOptions, dst []byte) ([]byte, *SpriteSheetManifest, error) {
	if opt == nil {
		opt = &SpriteSheetOptions{}
	}

	fileType := opt.FileType
	if fileType == "" {
		fileType = ".jpeg"
	}

	gridCols := opt.GridColumns
	if gridCols <= 0 {
		gridCols = SpriteSheetGridColumns
	}
	if gridCols > 100 { // safety bound
		gridCols = 100
	}

	tileMaxDim := opt.TileMaxDim
	if tileMaxDim <= 0 {
		tileMaxDim = SpriteSheetTileMaxDim
	}
	if tileMaxDim > 4096 { // safety bound
		tileMaxDim = 4096
	}

	absMaxTiles := opt.AbsoluteMaxTiles
	if absMaxTiles <= 0 {
		absMaxTiles = SpriteSheetAbsoluteMaxTiles
	}

	// Resolve the underlying avCodecDecoder so we can seek.
	avd, ok := d.(*avCodecDecoder)
	if !ok {
		return nil, nil, fmt.Errorf("spritesheet: decoder must be an avCodecDecoder (video source)")
	}

	hdr, err := d.Header()
	if err != nil {
		return nil, nil, fmt.Errorf("spritesheet: failed to read header: %w", err)
	}

	duration := d.Duration()
	if duration <= 0 {
		return nil, nil, fmt.Errorf("spritesheet: video has no duration")
	}

	srcW := hdr.Width()
	srcH := hdr.Height()
	if srcW <= 0 || srcH <= 0 {
		return nil, nil, fmt.Errorf("spritesheet: invalid video dimensions %dx%d", srcW, srcH)
	}

	timestamps := selectTimestamps(duration, opt.Rules, absMaxTiles)
	if len(timestamps) == 0 {
		return nil, nil, fmt.Errorf("spritesheet: no timestamps selected for duration %v", duration)
	}

	tileW, tileH := tileDimensions(srcW, srcH, tileMaxDim)

	rows := (len(timestamps) + gridCols - 1) / gridCols
	sheetW := tileW * gridCols
	sheetH := tileH * rows

	// Safety check: prevent allocating an enormously large canvas
	// 16384x16384 RGBA is ~1GB. Let's cap at 16384 for either dimension.
	if sheetW > 16384 || sheetH > 16384 {
		return nil, nil, fmt.Errorf("spritesheet: requested dimensions %dx%d exceed maximum allowed 16384x16384 to prevent memory exhaustion", sheetW, sheetH)
	}

	// Allocate the sprite sheet canvas as a 3-channel BGR mat.
	sheet := NewFramebuffer(sheetW, sheetH)
	defer sheet.Close()
	if err := sheet.Create3Channel(sheetW, sheetH); err != nil {
		return nil, nil, fmt.Errorf("spritesheet: failed to create canvas: %w", err)
	}
	// Zero-fill the canvas (black background).
	C.opencv_mat_reset(sheet.mat)

	// Allocate a reusable per-tile framebuffer, pre-initialized to video dimensions.
	// avcodec_decoder_copy_frame aligns the row stride to the next multiple of 32 pixels
	// when width%32 != 0, so the backing buffer must be large enough for the aligned stride.
	// Without this, opencv_mat_set_row_stride returns false and the decode silently fails
	// (returning black tiles).
	alignedSrcW := srcW
	if srcW%32 != 0 {
		alignedSrcW = srcW + 32 - (srcW % 32)
	}
	tileBufSize := alignedSrcW * srcH * 4
	tile := &Framebuffer{buf: make([]byte, tileBufSize)}
	defer tile.Close()
	if err := tile.resizeMat(srcW, srcH, PixelType(C.CV_8UC4)); err != nil {
		return nil, nil, fmt.Errorf("spritesheet: failed to initialize tile framebuffer: %w", err)
	}

	scaledTile := NewFramebuffer(tileW, tileH)
	defer scaledTile.Close()

	manifest := &SpriteSheetManifest{
		SheetWidth:  sheetW,
		SheetHeight: sheetH,
		TileWidth:   tileW,
		TileHeight:  tileH,
		GridColumns: gridCols,
		Tiles:       make([]SpriteSheetTile, 0, len(timestamps)),
	}

	for i, ts := range timestamps {
		col := i % gridCols
		row := i / gridCols
		destX := col * tileW
		destY := row * tileH

		// Seek and decode the frame at this timestamp.
		ok := bool(C.avcodec_decoder_seek_and_decode(avd.decoder, C.float(ts), tile.mat))
		if !ok {
			// On extraction failure, leave this tile black and continue.
			manifest.Tiles = append(manifest.Tiles, SpriteSheetTile{
				TimestampSec: ts,
				X:            destX, Y: destY,
				Width: tileW, Height: tileH,
			})
			continue
		}

		// Sync width/height from the mat in case seek+decode changed them.
		tile.width = int(C.opencv_mat_get_width(tile.mat))
		tile.height = int(C.opencv_mat_get_height(tile.mat))

		// Scale the decoded frame to tile dimensions.
		if err := tile.ResizeTo(tileW, tileH, scaledTile); err != nil {
			// Non-fatal: leave the tile black.
			manifest.Tiles = append(manifest.Tiles, SpriteSheetTile{
				TimestampSec: ts,
				X:            destX, Y: destY,
				Width: tileW, Height: tileH,
			})
			continue
		}

		// Copy the scaled tile into the correct position on the canvas.
		destRect := image.Rect(destX, destY, destX+tileW, destY+tileH)
		if err := sheet.CopyToOffsetNoBlend(scaledTile, destRect); err != nil {
			// Non-fatal.
			manifest.Tiles = append(manifest.Tiles, SpriteSheetTile{
				TimestampSec: ts,
				X:            destX, Y: destY,
				Width: tileW, Height: tileH,
			})
			continue
		}

		manifest.Tiles = append(manifest.Tiles, SpriteSheetTile{
			TimestampSec: ts,
			X:            destX, Y: destY,
			Width: tileW, Height: tileH,
		})
	}

	// Encode the assembled sprite sheet.
	// We pass the original decoder so NewEncoder can pull ICC/metadata;
	// the canvas itself is sRGB so no HDR override is needed.
	enc, err := NewEncoder(fileType, d, dst, nil)
	if err != nil {
		return nil, nil, fmt.Errorf("spritesheet: failed to create encoder: %w", err)
	}
	defer enc.Close()

	encOpts := opt.EncodeOptions
	if encOpts == nil {
		switch strings.ToLower(fileType) {
		case ".jpeg", ".jpg":
			encOpts = map[int]int{JpegQuality: 80}
		case ".webp":
			encOpts = map[int]int{WebpQuality: 85}
		case ".png":
			encOpts = map[int]int{PngCompression: 6}
		}
	}

	result, err := enc.Encode(sheet, encOpts)
	if err != nil {
		return nil, nil, fmt.Errorf("spritesheet: encode failed: %w", err)
	}

	return result, manifest, nil
}
